// Login
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

// LOGOUT
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// Register
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

// login_chack
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";
export const AUTH_GET_STATUS_VALUE = "AUTH_GET_STATUS_VALUE";


// design List
export const GET_DESIGN_LIST = "GET_DESIGN_LIST";
export const GET_DESIGN_DETAIL = "GET_DESIGN_DETAIL";

// group List
export const GET_GROUP_LIST = "GET_GROUP_LIST";
export const GET_GROUP_DETAIL = "GET_GROUP_DETAIL";

// designer List
export const GET_DESIGNER_LIST = "GET_DESIGNER_LIST";
export const GET_DESIGNER_DETAIL = "GET_DESIGNER_DETAIL";