const market_style = {
    font:{
        family:"Noto Sans KR",
        size:{
            // tiny1:"12px",
            // tiny2:"13px",
            // tiny3:"14px",
            // mini1:"15px",
            // mini2:"16px",
            // mini3:"17px",
            // small1:"18px",
            // small2:"19px",
            // small3:"20px",
            // normal1:"21px",
            // normal2:"22px",
            // normal3:"23px",
            // big1:"24px",
            // big2:"25px",
            // big3:"26px",
            // giant1:"27px",
            // giant2:"28px",
            // giant3:"29px",
            tiny1:"9px",
            tiny2:"10px",
            tiny3:"11px",
            mini1:"12px",
            mini2:"13px",
            mini3:"14px",
            small1:"15px",
            small2:"16px",
            small3:"17px",
            normal1:"18px",
            normal2:"19px",
            normal3:"20px",
            big1:"21px",
            big2:"22px",
            big3:"23px",
            giant1:"24px",
            giant2:"25px",
            giant3:"26px",
        }
    }
}
export default market_style 